#!/bin/bash

VER=$1
REL=$2
PKGNAME="xrootd-aggregatingname2name"

./create_targz ${VER}
rez=$?
[[ ${rez} == 1 ]] && { echo "Could not create targz"; exit 1;}

rpmdev-setuptree

mv -f ${PKGNAME}-${VER}.tar.gz $HOME/rpmbuild/SOURCES/
cp -f ${PKGNAME}.spec ${PKGNAME}.spec_wip

sed -i "/Version:/c\Version: ${VER}" ${PKGNAME}.spec_wip

[[ -n "${REL}" ]] && sed -i "/Release:/c\Release: ${REL}%{?dist}" ${PKGNAME}.spec_wip
mv ${PKGNAME}.spec_wip $HOME/rpmbuild/SPECS/${PKGNAME}.spec

cd $HOME/rpmbuild/SPECS
rpmbuild --define "debug_package %{nil}" -ba ${PKGNAME}.spec

